improve handling
```
ValueError: cannot mmap an empty file
Exception AttributeError: "'ProcDump' object has no attribute 'dumpfile'" in <bound method ProcDump.__del__ of <lib.cuckoo.common.objects.ProcDump object at 0x7f1f335aae10>> ignored
```

(cherry picked from commit 69fe5524b6c886fb9890370c7a34c49a9dd4ecc1)