OSError: [Errno 2] No such file or directory
similar as before but in tasks_dropped

(cherry picked from commit d0c1781c534411690c3560db976fdddf0d5f3b45)