fix IOError: image file is truncated (20 bytes not processed)
```
2018-10-09 20:04:06,064 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Deduplicate":
Traceback (most recent call last):
  File "$CUCKOO_ROOT/utils/../lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "$CUCKOO_ROOT/utils/../modules/processing/deduplication.py", line 68, in run
    screenshots = self.deduplicate_images(userpath=shots_path, hashfunc=hashfunc)
  File "$CUCKOO_ROOT/utils/../modules/processing/deduplication.py", line 40, in deduplicate_images
    hash = hashfunc(Image.open(img))
  File "$CUCKOO_ROOT/utils/../modules/processing/deduplication.py", line 64, in <lambda>
    hashfunc = lambda img: imagehash.whash(img, mode='db4')
  File "/usr/local/lib/python2.7/dist-packages/imagehash/__init__.py", line 260, in whash
    image = image.convert("L").resize((image_scale, image_scale), Image.ANTIALIAS)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 846, in convert
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 218, in load
    "(%d bytes not processed)" % len(b))
IOError: image file is truncated (20 bytes not processed)

```

(cherry picked from commit f82f70411865a01ed05741f6031f04f83216f38d)