Remove invalid character \xc2
File "/opt/CAPE/utils/../modules/signatures/network_doh.py", line 113
SyntaxError: Non-ASCII character '\xc2' in file /opt/CAPE/utils/../modules/sign
atures/network_doh.py on line 113, but no encoding declared; see http://python.
org/dev/peps/pep-0263/ for details

(cherry picked from commit 7216db12a0b3c529bbb957cecb1b33427ce18b2a)